name: Find
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flip_card: ^0.4.4
  google_fonts: ^1.0.0
  crypto: ^2.1.5
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  bottom_sheet: ^0.0.1-dev.7
  flutter_signin_button: ^1.1.0
  smart_select: ^4.3.2
  shared_preferences: ^0.5.7
  mobx: ^1.2.1+4
  flutter_svg: ^0.19.1
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.4
  modular_codegen: ^2.0.0
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "images/logo_app.png"
  image_path_ios: "images/logo_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/
